### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by lf237** [crisbeto/angular-svg-round-progressbar#65]
Hello,

Do you plan on adding angular 2 support in the future? Thanks.

**Comment by crisbeto** [comment]
I do. I'm waiting for them to get out of beta first.

**Comment by fbrcdx** [comment]
+1 Angular 2

**Comment by judenaveenraj** [comment]
+1 Would love Angular 2 support

**Comment by crisbeto** [comment]
Hey guys, I understand that people depend on this component, however I'm pretty busy atm. Unless something frees up earlier, I should have some time to take care of this around the end of July/early August.

**Comment by fbrcdx** [comment]
Thanks. 
_Meanwhile I've done the job with ng2-charts which is perfect. Same result for my needs and Ionic 2/Angular 2 compatible._

**Comment by Chuckv01** [comment]
@crisbeto We are very excited to see this ported to angular 2! I've looked around and nothing else currently out there for angular 2 comes close to this. :)

**Comment by Tyler-Darby** [comment]
Is there any news on this? Would really love to use this in a ng2 project.

**Comment by crisbeto** [comment]
There is, actually. [I started working on it over the weekend](https://github.com/crisbeto/angular-svg-round-progressbar/tree/ng2). I can't guarantee when it would be done since I'm still trying to figure out some stuff with Angular 2, but I'm trying to carve out time for it.

**Comment by Tyler-Darby** [comment]
Awesome, can't wait!

**Comment by Turv** [comment]
I'll be keeping an eye on this as I too would like to use it

**Comment by crisbeto** [comment]
I've got a somewhat working version on the ng2 branch, if you want to try it out. It's still missing some of the options, but `current`, `max`, `radius`, `animation`, `duration`, `stroke`, `color` and `background` are there. You might need to clone the repo since I haven't figured out how to keep both the Angular 1 and 2 version on NPM, yet.

**Comment by nowrap** [comment]
Hello,
i've installed the ng2 branch with the following command:
`npm install --save https://github.com/crisbeto/angular-svg-round-progressbar.git#ng2`

But i couldn't figure out, how can i use <round-progress> in my ionic 2 page correctly.

I tried in my pages.ts
`import { RoundProgress } from 'angular-svg-round-progressbar/src/round-progress';`
`@NgModule({
  imports: [RoundProgress]
})`

But i get an error:
`Error: Cannot find module "angular-svg-round-progressbar/src/round-progress"`

May someone provide me a hint to the correct way?

**Comment by crisbeto** [comment]
@nowrap it may be because the `ng2` branch doesn't have the built files, but I'm not too sure. It should work once I put it on NPM.

**Comment by Mjf94** [comment]
@nowrap Did you solve the problem? I want to use this component in my Ionic2 project but Chrome keeps saying `'RoundProgress' is not a known element:` 
I use the component in html directly.
Thanks.

**Comment by nowrap** [comment]
@Mjf94 regrettably not ;( 

Because i didn't have enough time, i tried https://github.com/subarroca/ng2-kw-gauge. Is less configurable, but worked in ionic 2.

**Comment by Mjf94** [comment]
@nowrap Thank you! However I still having trouble when importing the lib following the instruction. May you tell me how you add it to your project?

**Comment by Mjf94** [comment]
@nowrap Thanks! However I still have troubles when importing the lib following the instruction. The app cannot find the module as well. May you tell me how you use the lib?

**Comment by Tyler-Darby** [comment]
@crisbeto Having the same issue. Any recommendations?

**Comment by crisbeto** [comment]
I'm really sorry that this is taking so much to have it properly on NPM, but I've been caught up with some RL stuff (which should be resolved now) plus working on another project. This should be resolved once it's properly on NPM, which should be by Christmas **by the latest**.

**Comment by crisbeto** [comment]
Angular 2 support has been released under the `1.0.3` version. Please try it out and let me know if you encounter any issues.

**Comment by mobyjames** [comment]
Still unable to use with Ionic 2 when building for devices using the AoT compiler

`Error: Unexpected value 'RoundProgressModule' imported by the module 'AppModule' `

**Comment by vandres** [comment]
Same for verion 1.0.4

**Comment by JakubMitro** [comment]
it´s great feature ... still doesn´t work? Or guys do you have any advice for some alternative? I need to do gradient colour, customize background colour, customize width,.... :)

**Comment by CarlosTorrecillas** [comment]
I followed the Readme steps and couldn't get that to work in Angular 2. I used 'npm:angular-svg-round-progressbar/dist/round-progress.umd.js' instead of './node_modules/angular-svg-round-progressbar/dist/round-progress.umd.js'. The exception I get when I load the app is:

Error: Unexpected value 'undefined' imported by the module 'AppModule'...

**Comment by crisbeto** [comment]
Sorry guys, I've really busy with other projects. I'll try to get it resolved over the next few days.

**Comment by HartHerbert** [comment]
+1

**Comment by seiyria** [comment]
Unfortunately I'm also having AoT problems. @nowrap I can't seem to get kw-gauge working with AoT/Ionic 2 either.

**Comment by nowrap** [comment]
@seiyria I just followed the docs: https://github.com/subarroca/ng2-kw-gauge

**Comment by seiyria** [comment]
Yeah, I dunno. I just imported the module and tried to compile aot and it
broke.

**Comment by crisbeto** [comment]
I've published `1.0.5` to help with these issue. I've been testing it against the Angular 2 seed and it seems to work. Can somebody confirm?

**Comment by seiyria** [comment]
It does not seem to work for me. You can check out my project here: https://github.com/IdleLands/Play/tree/152a5a21bf3c604e57138ed71025e00c00327f2e 

Just have to run `npm install && npm run build:prod` (I hope).

**Comment by seiyria** [comment]
@crisbeto it looks like you need to publish your metadata.json files to make it work for other people.

**Comment by crisbeto** [comment]
Thanks for looking into it @seiyria. It means that I'll have to redo my build process a bit.

**Comment by sajTempler** [comment]
for Ionic 2 build there is similar issue.
just after `ngc started`

```
build prod failed: Unexpected value 'RoundProgressModule' imported by the module 'AppModule'
ionic-app-script task: "build"
Error: Unexpected value 'RoundProgressModule' imported by the module 'AppModule'
Error: Unexpected value 'RoundProgressModule' imported by the module 'AppModule'
```

[here ](https://github.com/sajTempler/testRoundProgress) repo with clean Ionic 2 where U can reproduce the issue

and the screen from build: 
![builderror](https://cloud.githubusercontent.com/assets/7117333/23699044/0bb1c7dc-03ee-11e7-924c-ff2e8be40a43.png)

**Comment by jltalens** [comment]
@sajTempler same here. The ts files need to be compiled with the ngc compiler rather than the tsc one... I'm working on a fix in a fork, if I manage to get it working I'm happy to make a PR

**Comment by crisbeto** [comment]
Can somebody give this a try? You can install it by extracting the ZIP file in your project and running `npm install angular-svg-round-progressbar-1.0.5.tgz` (I am aware that it's silly to put a tgz file in a zip, but Github doesn't allow tgz uploads).

[angular-svg-round-progressbar-1.0.5.tgz.zip](https://github.com/crisbeto/angular-svg-round-progressbar/files/841646/angular-svg-round-progressbar-1.0.5.tgz.zip)

**Comment by sajTempler** [comment]
Unfortunatelly it still fails:

![fail](https://cloud.githubusercontent.com/assets/7117333/23906770/3af08f2a-08cf-11e7-829d-c117f19c84bc.png)

**Comment by crisbeto** [comment]
Doesn't look like any of those files are referring to the progress module @sajTempler. Does it work if you don't require it?

**Comment by sajTempler** [comment]
@crisbeto  it seems to be some problem with minification not AoT compiling as I edited previous post with link

**Comment by crisbeto** [comment]
Looks like an Ionic issue. Can you try the AOT flag with the published version from NPM and the one I posted in the archive above?

**Comment by sajTempler** [comment]
@crisbeto I checked and version from npm doesn't work with `--aot` flag. Just the one U posted above works with `--aot` flag

**Comment by crisbeto** [comment]
Great, thanks for checking. It means that we're on the right track.

**Comment by sajTempler** [comment]
Okay I figured it out. For Ionic 2.

what U have to do is to change webpack config. You can easily add at the end of `package.json` :
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map_type": "source-map"
  }
```

and everything works like a charm ;D

**Comment by seiyria** [comment]
@sajTempler does that work with 1.0.5 or the zipped version above? Because all that really does is change some config, which doesn't necessarily apply if you already, f.ex, have a custom webpack config which does that.

**Comment by sajTempler** [comment]
@seiyria yes with that zipped version. Well it helped with Ionic 2.2.0 for prod, where everything was minified and so there was no source maps somehow needed for RoundProgress when building

**Comment by otherprod** [comment]
Same problem here, the "solution" to put  config in package.json doesnt work for me

**Comment by crisbeto** [comment]
I've released 1.0.6 that includes the new build process output. This means that it should have proper source maps, the metadata.json files and be AoT-compatible. Also here's Angular's "getting started" app which uses the round progress.

[toh-3.zip](https://github.com/crisbeto/angular-svg-round-progressbar/files/870445/toh-3.zip)

**Comment by vandres** [comment]
1.0.6 works for me with Ionic 2 in production mode

**Comment by seiyria** [comment]
Looks like it's letting me build now, nice job!

**Comment by HartHerbert** [comment]
why can't I install the plugin via the repository link? 
_https://github.com/crisbeto/angular-svg-round-progressbar.git_ 

After I enter this command `ionic plugin add https://github.com/crisbeto/angular-svg-round-progressbar.git` I only get this Error 

> Fetching plugin "https://github.com/crisbeto/angular-svg-round-progressbar.git" via git clone
> Repository "https://github.com/crisbeto/angular-svg-round-progressbar.git" checked out to git ref "master".
> Error: Failed to fetch plugin https://github.com/crisbeto/angular-svg-round-progressbar.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Cannot find plugin.xml for plugin "1490792196683". Please try adding it again.

**Comment by seiyria** [comment]
This is not a cordova plugin. Install it with npm.

**Comment by crisbeto** [comment]
Seeing that everything seems to be working with Angular 2+ now I'll close the issue since it's getting pretty big. If anything else comes up, please open another issue.
